### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by hgani** [lucaspiller/plain-david#7]
Hi,

Thank you for creating this gem. It has been an important part of my project.

Is there any plan to add support for Rails 5?

Thanks

**Comment by lucaspiller** [comment]
I don't have any plans right now, but feel free to submit a pull request
and I'll merge it in.

Have you tested it with Rails 5? A lot of things I've had to upgrade so far
mostly work out of the box.

Thanks!

**Comment by hgani** [comment]
@lucaspiller yes, I've tested with Rails 5 and got an error about an ActionMailer method that doesn't exist anymore in Rails 5.

I've commented out this gem temporarily to focus on getting the rest to work. I might give it another crack later.

Thanks

**Comment by hgani** [comment]
@lucaspiller I've asked my colleague to submit a pull request for this issue

https://github.com/lucaspiller/plain-david/pull/8

Please review

Thanks
